#! /bin/sh

NAME=ntpd
PROG=/usr/sbin/$NAME
DESC="busybox ntpd"
test -x $PROG || exit 0

startdaemon(){
        echo -n "Starting ntpd: "
        start-stop-daemon -b -S -q -m -p /var/run/ntpd.pid -x $PROG -- -N -p ntp5.aliyun.com -p 0.openwrt.pool.ntp.org
        echo "done"
}

stopdaemon(){
        echo -n "Stopping ntpd: "
        do_stop
        echo "done"
}

do_stop() {
        start-stop-daemon -K -q -p /var/run/ntpd.pid
        return 0
}

case "$1" in
        start)
                startdaemon
                ;;
        stop)
                stopdaemon
                ;;
        force-reload)
                stopdaemon
                startdaemon
                ;;
        restart)
                # Don't reset the tick here
                stopdaemon
                startdaemon
                ;;
        reload)
                # Must do this by hand, but don't do -g
                stopdaemon
                startdaemon
                ;;
        *)
                echo "Usage: ntpd { start | stop | restart | reload }" >&2
                exit 1
                ;;
esac

exit 0
