#ifndef _AW_AI_ERRORCODE_H
#define _AW_AI_ERRORCODE_H

#define AW_AI_ERROR_MEMALLOC_FAILURE 1001
#define AW_AI_ERROR_INVALID_HANDLE   1002
#define AW_AI_ERROR_INVALID_POINTER  1003
#define AW_AI_ERROR_UNSUPPORT_ABLITY 2001

#endif
