#ifndef WASHING_RES_CN_H_
#define WASHING_RES_CN_H_

//washing_win.c
#define ZNXIZJ "智能\n洗衣专家"
#define MIANMA "棉麻"
#define HUNHEXI "混合洗"
#define KUAIXI15 "快洗15’"
#define DAJIAN "大件"
#define CENSAN "衬衫"
#define HOUXINMEI "活性酶"
#define YANMAO "羊毛"
#define TONZHUAN "童装"
#define NEIYI "内衣"
#define YURONFU "羽绒服"
#define JIENEN "节能"
#define PIAOXITUOSHUI "漂洗+脱水"
#define DANTUOSHUI "单脱水"
#define DANHONGAN "单烘干"
#define XIHONG60 "洗烘60’"
#define KONGQIXI "空气洗"
#define JIANZIJIE "简自洁"

//washing des
#define MIANMA_N "日常棉麻衣物"
#define ZHINENG_P  "智能洗衣专家"
#define KUAIXI_N "微脏的少量衣物"
#define HUNHEXI_N  "日常不褪色衣物混合"
#define DAJIAN_N  "较厚重或较大的衣物"
#define CHENSHAN_N  "衬衫类衣物"
#define ZHINENG_N  "全智能感知:给衣物最好的洗涤"
#define HUOXINGMEI_N "较脏且耐洗的衣物"
#define YANGMAO_N "可机洗的羊毛类衣物"
#define TONGZHUANG_N "儿童类衣物"
#define NEIYI_N "内衣类衣物"
#define YURONGFU_N "可机洗的羽绒类衣物"
#define JIENENG_N "能耗相对较低"
#define PIAOXITUOSHUI_N "单独的漂洗加脱水"
#define DANTUOSHUI_N "单独的脱水程序"
#define DANHONGAN_N "单独的烘干程序"
#define XIHONG60_N "一次性洗烘\n微脏的少件衣物"
#define KONGQIXI_N "暖风清新衣物"
#define JIANZIJIE_N "特设的自清洁程序"

//slide_menu_win.c
#define TONSUO "童锁"
#define TONGDEN "筒灯"
#define WIFI "wifi"
#define WIFI_HINT1 "请输入"
#define WIFI_HINT2 "的密码"
#define WIFI_PASSWORD_ERROR "wifi密码不匹配"
#define WIFI_CONNECT_ERROR "wifi连接失败"
#define WIFI_READON "WIFI正在初始化中..."
#define SHUIGUANJIA "水管家"
#define YINLIAN "音量"
#define LIANDU "亮度"
#define YUYAN "语言"
#define SHIPING "视频"
#define CAOZUOZHIYIN "操作指引"
#define HUIFUMOREN "恢复默认"
#define YIWUBIAOZHI "衣物标识"
#define XIYIJIQIAO "洗衣技巧"

#define XIAOSHIYUYUE "小时预约"
#define WORLD_LEFT "预约至"
#define WORLD_RIGHT "小时后 结束洗衣"
#define WORLD_LEFT_BOTTOM "取消"
#define WORLD_RIGHT_BOTTOM "确定"
#define TONGSUO_N "长按3秒开启童锁"
#define QUXIAO_N "取消"
#define KAIQI_N "开启3秒"
#define YUYAN "语言"
#define ZHONGWEN "中文"
#define YINGWEN "英文"
#define SHIPIN_N "请插入SD卡"

//features_menu.c
#define YUYUE "预约"
#define XIDIJI "洗涤剂"
#define ROUSHUNJI "柔顺剂"
#define HONGGAN_M "烘干"
#define JIASUXI "加速洗"
#define TEZIXI "特渍洗"
#define JINGYINXI "静音洗"
#define WUTAIXI "雾态洗"

//bottombar_view.c
#define XIDI "洗涤"
#define DI "低"
#define ZHONG "中"
#define GAO "高"
#define SHUIWEI "水位"
#define CI "次"
#define PIAOXI "漂洗"
#define LENGSHUI "冷水"
#define DU "度"
#define WENDU "温度"
#define FEN "分"
#define TUOSHUI "脱水"
#define ZHUAN "转"
#define ZHUANSU "转速"
#define ZIDONG "自动"
#define MIANTUOSHUI "免脱水"
#define KAISHI "开始"
#define JIESHU "结束"
#define GONNENG "功能"

#define NET_WARNNING "播放网络视频失败,请连接WIFI"
#define NET_NATIVE "本地视频"
#define NET_URL "网络视频"
#endif /* WASHING_RES_CN_H_ */
