PRODUCT_PACKAGES += \
	libawavs \
	libawh264 \
	libawh265 \
	libawh265soft \
	libawmjpeg \
	libawmjpegplus \
	libawmpeg2 \
	libawmpeg4base \
	libawmpeg4dx \
	libawmpeg4h263 \
	libawmpeg4normal \
	libawmpeg4vp6 \
	libawvp6soft \
	libawvp8 \
	libawvp9soft \
        libawvp9Hw    \
	libawwmv12soft \
	libawwmv3 \
	libMemAdapter \
	libnormal_audio \
	libsdecoder \
	libvdecoder \
	libvideoengine \
	libVE \
	libvencoder \
	libOmxCore \
	libOmxVdec \
	libOmxVenc \
	libstagefrighthw \
