#ifndef _DBUS_SERVER_H_
#define _DBUS_SERVER_H_

typedef enum {
	NATIVEPOWER_DEAMON_GOTOSLEEP,
	NATIVEPOWER_DEAMON_ACQUIRE_WAKELOCK,
	NATIVEPOWER_DEAMON_RELEASE_WAKELOCK,
	NATIVEPOWER_DEAMON_SHUTDOWN,
	NATIVEPOWER_DEAMON_REBOOT,
	NATIVEPOWER_DEAMON_USERACTIVITY,
	NATIVEPOWER_DEAMON_SET_AWAKE_TIMEOUT,
	NATIVEPOWER_DEAMON_SET_SCENE,
	NATIVEPOWER_DEAMON_MAX,
} NativePower_Function;

void *dbus_server_thread_func(void *arg);

#endif
