all:
	mkdir -p $(INSTALL_PREFIX)/usr/lib
	mkdir -p $(INSTALL_PREFIX)/usr/bin

	cp *.so $(INSTALL_PREFIX)/usr/lib
	cp mdnsd_lebo $(INSTALL_PREFIX)/usr/bin
	cp dlna_app $(INSTALL_PREFIX)/usr/bin
	cp demo_player $(INSTALL_PREFIX)/usr/bin
	cp *.sh $(INSTALL_PREFIX)/usr/bin
