#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=98
STOP=98

USE_PROCD=1
PROG=smartlinkd

start_service() {
    procd_open_instance
    procd_set_param command $PROG -d
    procd_close_instance
}

stop_service() {
    procd_open_instance
    service=`ps | grep "smartlinkd -d" | grep -v grep`
    [ -n "$service" ] && {
        killall  smartlinkd
	sleep 1
    }
    procd_close_instance
}

restart() {
    stop $@
    start $@
}

shutdown() {
	echo shutdown
}
