#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
DEPEND=fstab,nativepower,mtp,adbd
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done
	[ -x /usr/bin/nativepower_utils ] && {
		nativepower_utils --module scene --set boot_complete
	}
}
