#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
STOP=98

USE_PROCD=1
PROG=/usr/bin/r11-board
MG_ENV=/etc/minigui.sh
DEPEND=boot
start_service() {
        procd_open_instance
	source $MG_ENV
        #procd_set_param command $PROG
	r11-board
        procd_close_instance
}

shutdown() {
        echo shutdown
}
