#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
STOP=98

USE_PROCD=1
PROG=/usr/bin/smart-music-player
DEPEND=boot

start_service() {
        procd_open_instance
        #procd_set_param command $PROG
        smart-music-player
        procd_close_instance
}

shutdown() {
        echo shutdown
}
