#ifndef _out_arm_plat_sun50iw1p1_include_generated_conf_h_
#define _out_arm_plat_sun50iw1p1_include_generated_conf_h_
#define CFG_8250_UART 1
#define CFG_ARCH_SUN50IW1P1 1
#define CFG_ARCH_SUNXI 1
#define CFG_ARM32_core 1
#define CFG_ARM32_ta_arm32 1
/* CFG_BOOT_SECONDARY_REQUEST is not set */
#define CFG_CACHE_API 1
#define CFG_CORE_CLUSTER_SHIFT 2
#define CFG_CORE_HEAP_SIZE 65536
/* CFG_CORE_LARGE_PHYS_ADDR is not set */
/* CFG_CORE_RODATA_NOEXEC is not set */
#define CFG_CORE_RWDATA_NOEXEC 1
/* CFG_CORE_SANITIZE_KADDRESS is not set */
/* CFG_CORE_SANITIZE_UNDEFINED is not set */
#define CFG_CORE_TZSRAM_EMUL_SIZE 458752
#define CFG_CRYPTO 1
#define CFG_CRYPTO_AES 1
#define CFG_CRYPTO_CBC 1
#define CFG_CRYPTO_CBC_MAC 1
#define CFG_CRYPTO_CCM 1
#define CFG_CRYPTO_CMAC 1
#define CFG_CRYPTO_CONCAT_KDF 1
#define CFG_CRYPTO_CTR 1
#define CFG_CRYPTO_CTS 1
#define CFG_CRYPTO_DES 1
#define CFG_CRYPTO_DH 1
#define CFG_CRYPTO_DSA 1
#define CFG_CRYPTO_ECB 1
#define CFG_CRYPTO_ECC 1
#define CFG_CRYPTO_GCM 1
#define CFG_CRYPTO_HKDF 1
#define CFG_CRYPTO_HMAC 1
#define CFG_CRYPTO_MD5 1
#define CFG_CRYPTO_PBKDF2 1
#define CFG_CRYPTO_RSA 1
#define CFG_CRYPTO_SHA1 1
#define CFG_CRYPTO_SHA224 1
#define CFG_CRYPTO_SHA256 1
#define CFG_CRYPTO_SHA384 1
#define CFG_CRYPTO_SHA512 1
#define CFG_CRYPTO_SIZE_OPTIMIZATION 1
#define CFG_CRYPTO_XTS 1
/* CFG_DT is not set */
#define CFG_DTB_MAX_SIZE 0x10000
#define CFG_DYN_SHM_CAP 1
/* CFG_EARLY_TA is not set */
/* CFG_ENABLE_SCTLR_RR is not set */
/* CFG_ENABLE_SCTLR_Z is not set */
#define CFG_GENERIC_BOOT 1
#define CFG_GP_SOCKETS 1
#define CFG_HWSUPP_MEM_PERM_PXN 1
#define CFG_HWSUPP_MEM_PERM_WXN 1
#define CFG_KERN_LINKER_ARCH arm
#define CFG_KERN_LINKER_FORMAT elf32-littlearm
#define CFG_LIBUTILS_WITH_ISOC 1
#define CFG_LPAE_ADDR_SPACE_SIZE (1ull << 32)
#define CFG_LTC_OPTEE_THREAD 1
#define CFG_MMAP_REGIONS 13
#define CFG_MSG_LONG_PREFIX_MASK 0x1a
#define CFG_NUM_THREADS 4
#define CFG_OPTEE_REVISION_MAJOR 2
#define CFG_OPTEE_REVISION_MINOR 5
/* CFG_PAGED_USER_TA is not set */
#define CFG_PM_STUBS 1
#define CFG_REE_FS 1
#define CFG_REE_FS_TA 1
/* CFG_RPMB_FS is not set */
#define CFG_RPMB_FS_DEV_ID 0
/* CFG_RPMB_WRITE_KEY is not set */
/* CFG_SCTLR_ALIGNMENT_CHECK is not set */
/* CFG_SECURE_DATA_PATH is not set */
#define CFG_SECURE_TIME_SOURCE_CNTPCT 1
#define CFG_SUNXI_CE10 1
#define CFG_SUNXI_EFUSE_ARCH64 1
#define CFG_SUNXI_NCAT 1
/* CFG_TA_FLOAT_SUPPORT is not set */
/* CFG_TA_GPROF_SUPPORT is not set */
#define CFG_TEE_API_VERSION GPD-1.1-dev
#define CFG_TEE_CORE_DEBUG 1
#define CFG_TEE_CORE_EMBED_INTERNAL_TESTS 1
#define CFG_TEE_CORE_LOG_LEVEL 1
/* CFG_TEE_CORE_MALLOC_DEBUG is not set */
#define CFG_TEE_CORE_TA_TRACE 1
#define CFG_TEE_CORE_USER_MEM_DEBUG 1
#define CFG_TEE_FW_IMPL_VERSION FW_IMPL_UNDEF
#define CFG_TEE_FW_MANUFACTURER FW_MAN_UNDEF
#define CFG_TEE_IMPL_DESCR OPTEE
#define CFG_TEE_MANUFACTURER LINARO
#define CFG_TEE_TA_LOG_LEVEL 1
/* CFG_TEE_TA_MALLOC_DEBUG is not set */
/* CFG_ULIBS_GPROF is not set */
#define CFG_UNWIND 1
#define CFG_WITH_ARM_TRUSTED_FW 1
/* CFG_WITH_PAGER is not set */
#define CFG_WITH_SOFTWARE_PRNG 1
#define CFG_WITH_STACK_CANARIES 1
#define CFG_WITH_USER_TA 1
#define PLATFORM_FLAVOR sun50iw1
#define PLATFORM_FLAVOR_sun50iw1 1
#define PLATFORM_sun50iw1p1 1
#define _CFG_CRYPTO_WITH_ACIPHER 1
#define _CFG_CRYPTO_WITH_ASN1 1
#define _CFG_CRYPTO_WITH_AUTHENC 1
#define _CFG_CRYPTO_WITH_CBC 1
#define _CFG_CRYPTO_WITH_CIPHER 1
#define _CFG_CRYPTO_WITH_FORTUNA_PRNG 1
#define _CFG_CRYPTO_WITH_HASH 1
#define _CFG_CRYPTO_WITH_MAC 1
#endif
