#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs none /dev

exec < /dev/console > /dev/console 2>&1

for parm in $(cat /proc/cmdline); do
	case $parm in
	ramfs)
		RAMFS_MODE=1
		;;
	ota=*)
		OTA_MODE=`echo $parm | awk -F\= '{print $2}'`
		;;
	esac
done

[ "x$RAMFS_MODE" = "x1" ] && /bin/sh

[ "x$OTA_MODE" = "x1" ] &&  exec /init_ota

exec /init_sunxi
