#ifndef _MIDEA_MAIN_H_
#define _MIDEA_MAIN_H_

typedef enum{
	ASR_UART_CMD_WAKE_UP 		= 0x0,
	ASR_UART_CMD_CLOSE_RECOG	= 0x01,
	ASR_UART_CMD_ON		 		= 0x02,
	ASR_UART_CMD_OFF	 		= 0x03,

	/*set mode*/
	ASR_UART_CMD_SET_MODE_AUTO 	= 0x04,
	ASR_UART_CMD_SET_MODE_COOL 	= 0x05,
	ASR_UART_CMD_SET_MODE_DRY 	= 0x06,
	ASR_UART_CMD_SET_MODE_HEAT 	= 0x07,
	ASR_UART_CMD_SET_MODE_WIND 	= 0x08,

	/*set temperature*/
	ASR_UART_CMD_SET_TEMP_17 	= 0x09,
	ASR_UART_CMD_SET_TEMP_18 	= 0x0A,
	ASR_UART_CMD_SET_TEMP_19 	= 0x0B,
	ASR_UART_CMD_SET_TEMP_20 	= 0x0C,
	ASR_UART_CMD_SET_TEMP_21 	= 0x0D,
	ASR_UART_CMD_SET_TEMP_22 	= 0x0E,
	ASR_UART_CMD_SET_TEMP_23 	= 0x0F,
	ASR_UART_CMD_SET_TEMP_24 	= 0x10,
	ASR_UART_CMD_SET_TEMP_25 	= 0x11,
	ASR_UART_CMD_SET_TEMP_26 	= 0x12,
	ASR_UART_CMD_SET_TEMP_27 	= 0x13,
	ASR_UART_CMD_SET_TEMP_28 	= 0x14,
	ASR_UART_CMD_SET_TEMP_29 	= 0x15,
	ASR_UART_CMD_SET_TEMP_30 	= 0x16,
	
	ASR_UART_CMD_INC_T_BY_1		= 0x17,
	ASR_UART_CMD_INC_T_BY_3		= 0x18, /*too cold*/
	ASR_UART_CMD_DEC_T_BY_1		= 0x19,
	ASR_UART_CMD_DEC_T_BY_3		= 0x1A, /*too hot*/

	/*set wind */
	ASR_UART_CMD_WIND_SLOW 		= 0x1B,
	ASR_UART_CMD_WIND_MID 		= 0x1C,
	ASR_UART_CMD_WIND_HIGH 		= 0x1D,
	ASR_UART_CMD_WIND_AUTO		= 0x1E,
	
	ASR_UART_CMD_WINDLESS_ON	= 0x1F,
	ASR_UART_CMD_WINDLESS_OFF	= 0x20,

	ASR_UART_CMD_FIRST_OPEN_INFO	= 0x21, /*ASR on, play notify info*/
	ASR_UART_CMD_IDLE_TIMEOUT_INFO	= 0x22, /*15s timeout, play notify info*/
}ASR_FRAME_CMD_ID;

#endif

